# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-07 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvscripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='footnote',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='position',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
