# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-10 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvscripts', '0003_auto_20170607_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='epi_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
