# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-10 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvscripts', '0004_script_epi_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='scripts',
            field=models.CharField(max_length=5000),
        ),
    ]
