# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-06 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170506_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfeaturedimage',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.PostFeaturedImage'),
        ),
    ]
