# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-06 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170506_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfeaturedimage',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postfeaturedimage',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='postfeaturedimage',
            name='image',
            field=models.ImageField(height_field='height_field', upload_to='images/%Y/%m/%d', width_field='width_field'),
        ),
    ]
