# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-07 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20170507_1846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostFeaturedImage',
        ),
    ]
